### ISSUE TITLE
Pass in react component for list renderer

### ISSUE THREAD

**Issue by MDSL-Dev** [oozou/slate-suggestions#12]
It would be very flexible if I could pass through a React component for the <ul/> so that I can get finer grain control over how the list dropdown looks, and would avoid needing CSS hacks to style the UI.

Love what you're doing with this library!

**Comment by aunsuwijak** [comment]
@MDSL-Dev Actually you can pass react component as dropdown item.

**Comment by MDSL-Dev** [comment]
Is this documented?

**Comment by aunsuwijak** [comment]
@MDSL-Dev Oh my bad. I put it in example, but not it README. Thanks for noticing.

**Comment by aunsuwijak** [comment]
@MDSL-Dev README updated.
