### ISSUE TITLE
Remote data

### ISSUE THREAD

**Issue by mxstbr** [oozou/slate-suggestions#18]
Is there any way to fetch the suggestions from a server rather than having them in an object locally? I couldn't find anything in the docs...

**Comment by oyeanuj** [comment]
I think @bkniffler mentioned he was working on fetch function being a promise, in #14

**Comment by marekolszewski** [comment]
@mxstbr Check out my [PR](https://github.com/oozou/slate-suggestions/pull/20) which adds this functionality. Simply set suggestions to a function that takes the current partially completed text and returns a promise (resolving to a suggestions array).
