### ISSUE TITLE
use trigger in the middle of the node issue

### ISSUE THREAD

**Issue by khanhhaduc** [oozou/slate-suggestions#9]
when I tried to use the trigger '@' in the middle of the node, the SuggestionPortal did not appear,
the text from '@' to the end of that node got delete and only @ was added.

**Comment by aunsuwijak** [comment]
Thanks @khanhhaduc, Can you provide an example of the code that replicate the issue?

**Comment by khanhhaduc** [comment]
Hi, here's the relevant bit in my code

`export default class App extends Component {
	constructor() {
		super();
		this.suggestionsPlugin = SuggestionsPlugin({
			trigger: '@',
			capture: /@([\w]*)/,
			suggestions,
			onEnter: (suggestion) => {
				console.log('called');
				const { state } = this.state;
				const { anchorText, anchorOffset } = state;

				const text = anchorText.text;

				let index = { start: anchorOffset - 1, end: anchorOffset };

				if (text[anchorOffset - 1] !== '@') {
					index = getCurrentWord(text, anchorOffset - 1, anchorOffset - 1);
				}

				const newText = `${text.substring(0, index.start)}${suggestion.value} ${text.substring(index.end)}`;

				return state
					.transform()
					.deleteBackward(anchorOffset)
					.insertText(newText)
					.apply();
			}
		});
	}`

...

`render() {
		const { SuggestionPortal } = this.suggestionsPlugin;

		return (
				<div className="editor">
					<Editor
						plugins={[this.suggestionsPlugin, ...plugins]}
						schema={this.state.schema}
						state={this.state.state}
						onChange={state => this.setState({ state })}
					/>
					<SuggestionPortal state={this.state.state} />
				</div>
		);
	}
`

**Comment by khanhhaduc** [comment]
It works fine when I start typing the trigger at the end of the node 
![works fine](https://cloud.githubusercontent.com/assets/6720949/21631138/d8a50ebc-d29c-11e6-9953-05bdf32db44e.png)

Only when I try to do it in the middle (of the same node), the cursor got moved, also the text from the trigger is deleted and the portal wouldn't show up:
![something wrong](https://cloud.githubusercontent.com/assets/6720949/21631147/f6ebdc34-d29c-11e6-977a-2ed45cf86781.png)

**Comment by aunsuwijak** [comment]
Thanks @khanhhaduc, will fix very soon.

**Comment by khanhhaduc** [comment]
Thanks a lot for the quick response :)

**Comment by aunsuwijak** [comment]
This problem is causes by https://github.com/ianstormtaylor/slate/issues/533, I fix it by replace undesirable state created by selection-position in onChange method with current editor state according to this pull request https://github.com/oozou/slate-suggestions/pull/10. If you have any suggestion please let me know.
